// This file is auto-generated by analyze script
export const brands = [
  "AMERICAN EXPRESS",
  "ARGENCARD",
  "ATM CARD",
  "AURA",
  "BANKCARD(INACTIVE)",
  "BELKART",
  "BP FUEL CARD",
  "CABAL",
  "CARNET",
  "CHINA UNION PAY",
  "CHINA UNION PAY/UZCARD",
  "CHJONES FUEL CARD",
  "CIRRUS",
  "CMI",
  "CODENSA",
  "COMPROCARD",
  "DANKORT",
  "DINACARD",
  "DINERS CLUB INTERNATIONAL",
  "DISCOVER",
  "DUET",
  "EBT",
  "EFTPOS",
  "ELO",
  "EUROSHELL FUEL CARD",
  "FUEL CARD",
  "GE CAPITAL",
  "GIROCARD",
  "GLOBAL BC",
  "HIPERCARD",
  "HUMOCARD",
  "JCB",
  "JCB/CHINA UNION PAY",
  "JCB/LANKAPAY",
  "JCB/MIR",
  "JCB/RUPAY",
  "LOCAL BRAND",
  "LOYALTY CARD",
  "LUKOIL FUEL CARD",
  "MAESTRO",
  "MAESTRO/BANCONTACT",
  "MASTERCARD",
  "MASTERCARD/BANCONTACT",
  "MEEZA",
  "NEWDAY",
  "NSPK MIR",
  "OUROCARD",
  "PAGOBANCOMAT",
  "PAYPAK",
  "PAYPAL",
  "PHH FUEL CARD",
  "PRIVATE LABEL",
  "PROSTIR",
  "RED FUEL CARD",
  "RED LIQUID FUEL CARD",
  "RUPAY",
  "SBERCARD",
  "SODEXO",
  "STAR REWARDS",
  "TARJETA CENCOSUD",
  "TARJETA NARANJA",
  "TROY",
  "UATP",
  "UK FUEL CARD",
  "UZCARD",
  "VERVE",
  "VISA",
  "VISA/BANCONTACT",
  "VISA/DANKORT",
  "VOYAGER",
  "VPAY",
  "WEXCARD"
];

export const levels = [
  "AARP",
  "ACCESS",
  "ACH FOR CONSUMER",
  "ACQUIRER ONLY",
  "ACTIVATION VERIFICATION",
  "AGRICULTURAL",
  "AGRO",
  "AIR",
  "AIRMILES PREMIER",
  "ALGERIA",
  "ALIMENTACAO",
  "ALL-IN-ONE CARD",
  "ANDORRA",
  "ANTIGUA AND BARBUDA",
  "ARGENTINA",
  "ARMED POLICE SERVICEMAN GUARANTEE CARD",
  "ARMENIA",
  "ARUBA",
  "ATM",
  "ATM CARD",
  "AUSTRALIA",
  "AUSTRIA",
  "AUTO",
  "AWARD",
  "B2B",
  "B2B VIRTUAL",
  "B2B VIRTUAL PAYMENTS",
  "BAHAMAS",
  "BAHRAIN",
  "BANGLADESH",
  "BARBADOS",
  "BASIC",
  "BASICO",
  "BC CARD",
  "BELGIUM",
  "BELIZE",
  "BERMUDA",
  "BILL PAY COMMERCIAL",
  "BIN WALLET MOBILE PAYMENT",
  "BLACK",
  "BLACK DIGITAL",
  "BLUE",
  "BLUE AIRMILES CASH BACK CARD",
  "BNDES",
  "BOLIVIA",
  "BOSNIA AND HERZEGOVINA",
  "BOTSWANA",
  "BRAZIL",
  "BRUNEI DARUSSALAM",
  "BULGARIA",
  "BUSAN BC CARD",
  "BUSAN BC CHECK",
  "BUSINESS",
  "BUSINESS ELO MORE",
  "BUSINESS ENHANCED",
  "BUSINESS GRAPHITE",
  "BUSINESS INFINITE",
  "BUSINESS NANJING DINERS",
  "BUSINESS PLATINUM",
  "BUSINESS PREFERRED",
  "BUSINESS REWARDS",
  "BUSINESS SIGNATURE",
  "BUSINESS TRAVEL",
  "BUSINESS WORLD",
  "CAMBODIA",
  "CANADA",
  "CARTE CIB",
  "CARTE DE RETRAIT JEUNE",
  "CARTE PRIVATIVE",
  "CARTE PRIVATIVE EPARGNE",
  "CARTE PRIVATIVE PIN ON-LINE",
  "CASH",
  "CAYMAN ISLANDS",
  "CENTRAL TRAVEL SOLUTIONS AIR",
  "CENTRAL TRAVEL SOLUTIONS LAND",
  "CENTURION",
  "CENTURY CARD",
  "CHARGE CARD",
  "CHENXING CARD",
  "CHILE",
  "CHINA",
  "CHINESE ROSE CARD",
  "CHUFA CARD",
  "CIRRUS",
  "CITI CARDS",
  "CITIBANK CARD",
  "CITIZEN CARD",
  "CITY CARD",
  "CLASSIC",
  "CLASSIC/GOLD",
  "CLASSIC/PLATINUM",
  "CLASSIC/SIGNATURE",
  "CMI",
  "COLOMBIA",
  "COMBO",
  "COMMERCIAL",
  "COMMERCIAL AGRICULTURE",
  "COMMERCIAL BILL PAY",
  "COMMERCIAL MARKETPLACE",
  "COMMERCIAL PAYMENT ACCOUNT",
  "COMMERCIAL PUBLIC SECTOR",
  "COMMERCIAL REWARD FUNDING",
  "COMMERCIAL TRANSPORT",
  "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
  "CONSTRUCARD",
  "CONSUMER",
  "CONSUMER LENDING",
  "COOK ISLANDS",
  "COOPERATIVE CARD",
  "CORPORATE",
  "CORPORATE DINERS",
  "CORPORATE EXECUTIVE",
  "CORPORATE FLEET",
  "CORPORATE GOLD",
  "CORPORATE GOLD CHARGE",
  "CORPORATE GREEN REVOLVE",
  "CORPORATE MEETING",
  "CORPORATE NANJING",
  "CORPORATE NANJING DINERS",
  "CORPORATE PURCHASING",
  "CORPORATE T&E",
  "CORPORATE WORLD",
  "CORPORATE WORLD ELITE",
  "CORPORATE/INFINITE",
  "COSTA RICA",
  "CREDIT",
  "CREDIT COEMITIDA",
  "CROATIA",
  "CULTURA",
  "CURACAO",
  "CYPRUS",
  "CZECH REPUBLIC",
  "DAEGU BC CARD",
  "DAEGU BC CHECK",
  "DALIAN SOCIAL SECURITY CARD",
  "DATANGKA",
  "DEBIT",
  "DEFERRED DEBIT",
  "DELAYED DEBIT",
  "DENMARK",
  "DEPARTMENT STORE CARD",
  "DIAMOND",
  "DIGITAL ENABLEMENT PROGRAM",
  "DIRECT PAYOUTS TO BANK ACCOUNTS",
  "DISTRIBUTION",
  "DOMINICA",
  "DOMINICAN REPUBLIC",
  "ECUADOR",
  "EGYPT",
  "EL SALVADOR",
  "ELECTRIC ORANGE",
  "ELECTRON",
  "ELECTRONIC",
  "ELECTRONIC BUSINESS",
  "ELECTRONIC COMMERCIAL",
  "ELO MORE",
  "EMERALD",
  "EMERGING CARD",
  "EMPRESARIAL ELO MORE",
  "ENHANCED",
  "ENTERPRISE SOLUTIONS",
  "ESTONIA",
  "EXECUTIVE",
  "EXECUTIVE BUSINESS",
  "EXECUTIVE CORPORATE",
  "FINANCIAL PLAN CARD",
  "FINLAND",
  "FIRSTMONIE COMPANION",
  "FLEET",
  "FLEET CONSUMER",
  "FLEXIA",
  "FOOD",
  "FOOD CARD",
  "FRANCE",
  "FSA",
  "GEN CARD NUMBERS",
  "GEORGIA",
  "GERMANY",
  "GHANA",
  "GIFT",
  "GIFT VOUCHER",
  "GLOBAL PAYMENT",
  "GM CARD",
  "GNS GOLD CHARGE",
  "GNS GREEN CHARGE",
  "GNS NETWORK CARD",
  "GNS PLATINUM CHARGE",
  "GOLD",
  "GOLD BUSINESS",
  "GOLD DIGITAL",
  "GOLD/CORPORATE",
  "GOLD/PLATINUM",
  "GOLDEN BRIDGE CARD",
  "GOLDEN SPIKE",
  "GOVERNMENT COMMERCIAL",
  "GOVERNMENT CORPORATE T&E",
  "GOVERNMENT PURCHASING",
  "GOVERNMENT PURCHASING WITH FLEET",
  "GPP",
  "GRAPHITE",
  "GREECE",
  "GREEN",
  "GREEN LEAF CARD",
  "GRENADA",
  "GRMS CORPORATE CONTROL",
  "GUANGZHOU CARD",
  "GUANGZHOU CREDIT",
  "GUATEMALA",
  "GUYANA",
  "GYEONGNAM BC CARD",
  "HAN SKBC CARD",
  "HAN SKBC CHECK",
  "HANA CARD",
  "HEALTHCARE",
  "HELOC PLATINUM",
  "HELOC STANDARD",
  "HENGTONG CARD",
  "HONDURAS",
  "HONG KONG",
  "HOTEL",
  "HSA NON SUBSTANTIATED",
  "HUITONG CARD",
  "HUNGARY",
  "HYUNDAI CARD",
  "IBK BC CARD",
  "IBK BC CHECK",
  "IBK COMPANIES BC",
  "IBK INDUSTRIAL BANK",
  "IC CARD",
  "ICARD",
  "ICELAND",
  "IDENTITY",
  "IKEA CARD",
  "IMMEDIATE DEBIT",
  "INDIA",
  "INDIVIDUAL",
  "INDONESIA",
  "INFINITE",
  "INFINITE BUSINESS",
  "INFINITE PRIVILEGE",
  "INFINITE/PLATINUM",
  "INFINITE/SIGNATURE",
  "INSTALLMENT PAYMENTS P",
  "INSTALLMENT PAYMENTS S",
  "INSTALLMENTS PREMIUM",
  "INSTALMENT PREMIUM",
  "INTERNET BANKING CODE CARD",
  "INVALID",
  "IRAN",
  "IRAN, ISLAMIC REPUBLIC OF",
  "IRAQ",
  "IRELAND",
  "ISIC",
  "ISIC STUDENT",
  "ISRAEL",
  "ITALY",
  "JAMAICA",
  "JAPAN",
  "JEONBUK CARD",
  "JIAXIU CARD",
  "JIHE CARD",
  "JINDA CARD",
  "JINRUI CARD",
  "JINSHAN MONEY LINK CARD",
  "JORDAN",
  "KAZAKHSTAN",
  "KB KOOKMIN CARD",
  "KB NATIONAL BC CARD",
  "KENYA",
  "KIM BIKA",
  "KIRIN CARD",
  "KOREA REPUBLIC OF",
  "KOREA, REPUBLIC OF",
  "KUWAIT",
  "KYUSHU DEBIT",
  "LATVIA",
  "LEBANON",
  "LITHUANIA",
  "LOTTE CORPORATION",
  "LOTTE PENTA",
  "LOTTE WEAVER SKY",
  "LOWES CARD",
  "LUXEMBOURG",
  "MACAO",
  "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
  "MAESTRO",
  "MALAYSIA",
  "MALDIVES",
  "MALTA",
  "MASTERMONEY",
  "MAURITIUS",
  "MEEZA",
  "MEXICO",
  "MICRO BUSINESS",
  "MINZHOU CARD",
  "MIXED",
  "MIXED BIN",
  "MIXED PRODUCT",
  "MOROCCO",
  "MOZAMBIQUE",
  "MUJER ACTIVA",
  "MULTIPLO",
  "NAMIBIA",
  "NANJING",
  "NANJING DINERS",
  "NATIONAL CUP ENTERPRISE CARD",
  "NEPAL",
  "NETHERLANDS",
  "NETWORK CARDS",
  "NEW WORLD",
  "NEW ZEALAND",
  "NH CARD",
  "NH CHECK CARD",
  "NH CORPORATE CARD",
  "NH NONGHYUP BC CARD",
  "NH NONGHYUP CHECK",
  "NH PLATINUM",
  "NICARAGUA",
  "NIGERIA",
  "NORWAY",
  "NPF VERVE NFC",
  "OMAN",
  "ONE CHECK CARD",
  "ONE COMPANY CHECK",
  "ONE CORPORATE CARD",
  "OPEN BLUE REVOLVE",
  "OPEN GOLD CHARGE",
  "OPEN GOLD REVOLVE",
  "OPEN GREEN CHARGE",
  "OPEN GREEN REVOLVE",
  "OPEN PLATINUM REVOLVE",
  "OPTIMA",
  "ORIENTAL CARD",
  "OTHER",
  "OUR CARD",
  "OUR CHECK CARD",
  "PACIFIC",
  "PAGAMENTO FORNECEDORES",
  "PAKISTAN",
  "PANAMA",
  "PAPUA NEW GUINEA",
  "PARAGUAY",
  "PAYMENT CARD",
  "PAYPASS",
  "PAYPASS CARD",
  "PENSION",
  "PEONY MONEY LINK",
  "PEONY QUASI-CREDIT CARD",
  "PERSONAL",
  "PERSONAL BLACK CHARGE",
  "PERSONAL BLUE CHARGE",
  "PERSONAL BLUE REVOLVE",
  "PERSONAL CHARGE",
  "PERSONAL CORE",
  "PERSONAL GOLD CHARGE",
  "PERSONAL GOLD REVOLVE",
  "PERSONAL GREEN CHARGE",
  "PERSONAL GREEN PREPAID",
  "PERSONAL GREEN REVOLVE",
  "PERSONAL PLATINUM CHARGE",
  "PERSONAL PLATINUM REVOLVE",
  "PERSONAL REVOLVE",
  "PERU",
  "PHILIPPINES",
  "PIN ONLY W/O EBT",
  "PJ PAYMENT ACCOUNT",
  "PLATINUM",
  "PLATINUM DIGITAL",
  "PLATINUM FLEX",
  "PLATINUM REWARDS",
  "PLATINUM SALARY",
  "PLATINUM/STANDARD",
  "PMJDY",
  "POLAND",
  "PORTUGAL",
  "PREFERRED BUSINESS",
  "PREMIUM",
  "PREMIUM PLUS",
  "PREPAID",
  "PREPAID ANONYMOUS",
  "PREPAID AWARDS",
  "PREPAID B2B",
  "PREPAID B2B VIRTUAL",
  "PREPAID BUSINESS",
  "PREPAID BUSINESS ELECTRONIC",
  "PREPAID BUSINESS PREFERRED",
  "PREPAID CASH",
  "PREPAID CLASSIC",
  "PREPAID COMMERCIAL",
  "PREPAID COMMERCIAL AGRICULTURE",
  "PREPAID COMMERCIAL PAYMENT ACCOUNT",
  "PREPAID COMMERCIAL TRANSPORT",
  "PREPAID CONSUMER",
  "PREPAID CONSUMER INCENTIVE",
  "PREPAID CORPORATE",
  "PREPAID CORPORATE T&E",
  "PREPAID DIRECT PAYOUTS TO WALLETS",
  "PREPAID ELECTRON",
  "PREPAID ELECTRONIC",
  "PREPAID EMPLOYEE INCENTIVE",
  "PREPAID FLEX",
  "PREPAID FLEX BENEFIT",
  "PREPAID GOLD",
  "PREPAID GOLD PAYROLL",
  "PREPAID GOVERNMENT",
  "PREPAID GOVERNMENT CORPORATE T&E",
  "PREPAID GOVERNMENT PURCHASING",
  "PREPAID HEALTHCARE",
  "PREPAID HEALTHCARE NON TAX",
  "PREPAID HEALTHCARE NON-TAX",
  "PREPAID HORIZON CLASSIC",
  "PREPAID HSA SUBSTANTIATED",
  "PREPAID HUMANITARIUM",
  "PREPAID INSURANCE",
  "PREPAID ISIC",
  "PREPAID MEAL",
  "PREPAID NON-RELOADABLE",
  "PREPAID PAYROLL",
  "PREPAID PEDAGIO",
  "PREPAID PLATINUM",
  "PREPAID PLATINUM TRAVEL",
  "PREPAID PREFERRED BUSINESS",
  "PREPAID PREMIUM TRAVEL",
  "PREPAID PRIVATE LABEL",
  "PREPAID PRIVATE LABEL BASIC",
  "PREPAID PRIVATE LABEL ENHANCED",
  "PREPAID PRIVATE LABEL PREMIUM",
  "PREPAID PRIVATE LABEL STANDARD",
  "PREPAID PROPRIETARY ATM",
  "PREPAID PURCHASING",
  "PREPAID PURCHASING WITH FLEET",
  "PREPAID RELOADABLE",
  "PREPAID REWARDS",
  "PREPAID SELECT",
  "PREPAID SMALL BUSINESS",
  "PREPAID TEEN",
  "PREPAID TRAVEL",
  "PREPAID TRAVEL MONEY",
  "PREPAID V PAY",
  "PREPAID VIRTUAL",
  "PREPAID VOUCHER",
  "PREPAID VPAY",
  "PREPAID WORKPLACE B2B",
  "PREPAID WORKPLACE BENEFITS",
  "PREPAID WORLD",
  "PREPAID XPLORER",
  "PRIORITY PLATINUM",
  "PRIVATE LABEL",
  "PRIVATE LABEL BASIC",
  "PRIVATE LABEL H",
  "PRIVATE LABEL TRADE PROGRAM",
  "PROFESSIONAL",
  "PROPEIETARY",
  "PROPRIETARY",
  "PROPRIETARY ATM",
  "PROPRIETARY/STANDARD",
  "PUERTO RICO",
  "PURCHASES",
  "PURCHASING",
  "PURCHASING WITH FLEET",
  "Q-CASH",
  "Q-CASH GENERAL",
  "QATAR",
  "QC STAFF",
  "QILU CARD",
  "QINGYUN CARD",
  "QUANTUM",
  "RETRAIT",
  "RETRAIT INTERNE",
  "REWARDS",
  "RMB CARD",
  "ROMANIA",
  "ROSE CARD",
  "RUPAY SELECT",
  "RUSSIAN FEDERATION",
  "SAINT KITTS AND NEVIS",
  "SAINT LUCIA",
  "SALARY",
  "SALUTE",
  "SAMOA",
  "SAMSUNG CARD",
  "SAMSUNG CHECK",
  "SAMSUNG CHECK CARD",
  "SAUDI ARABIA",
  "SC BC CARD",
  "SC BC CHECK",
  "SEARS",
  "SELECT",
  "SENEGAL",
  "SERBIA",
  "SEYCHELLES",
  "SHINHAN BC CARD",
  "SHINHAN BC CHECK",
  "SHINHAN CARD",
  "SHINHAN CARD - CHECK",
  "SHINHAN CARD - CORPORATE",
  "SHOP & SPLIT",
  "SIGNATURE",
  "SIGNATURE BUSINESS",
  "SIGNATURE PREFERRED",
  "SILVER",
  "SINGAPORE",
  "SINT MAARTEN",
  "SLOVAKIA",
  "SLOVENIA",
  "SMALL BUSINESS",
  "SMALL CORPORATE",
  "SOCIAL SECURITY CARD",
  "SOCIAL SECURITY IC CARD",
  "SOLOMON ISLANDS",
  "SOUTH AFRICA",
  "SPAIN",
  "SPRING CITY CARD",
  "SRI LANKA",
  "SSANGYONG CARD",
  "STANDARD",
  "STANDARD - UNEMBOSSED",
  "STANDARD DIGITAL",
  "STANDARD SALARY",
  "STANDARD/GOLD/TITANIUM",
  "STANDARD/PLATINUM/WORLD",
  "STUDENT",
  "SUPPLIERS PAYMENT",
  "SUPREME",
  "SURINAME",
  "SWEDEN",
  "SWITZERLAND",
  "SYRIAN ARAB REPUBLIC",
  "TAIWAN PROVINCE OF CHINA",
  "TAIWAN, PROVINCE OF CHINA",
  "TANZANIA UNITED REPUBLIC OF",
  "TANZANIA, UNITED REPUBLIC OF",
  "THAILAND",
  "TITANIUM",
  "TITANIUM/GOLD",
  "TONGA",
  "TRADITIONAL",
  "TRADITIONAL REWARDS",
  "TRAVEL MONEY",
  "TRINIDAD AND TOBAGO",
  "TUNISIA",
  "TURKEY",
  "TURKS AND CAICOS ISLANDS",
  "UATP",
  "UGANDA",
  "UHNW",
  "UKRAINE",
  "ULTIMATE",
  "ULTRA HIGH NET WORTH",
  "UNEMBOSSED",
  "UNIONPAY CARD",
  "UNIT SETTLEMENT CARD",
  "UNITED ARAB EMIRATES",
  "UNITED KINGDOM",
  "UNITED STATES",
  "URUGUAY",
  "V PAY",
  "VANUATU",
  "VENEZUELA, BOLIVARIAN REPUBLIC OF",
  "VERVE",
  "VERVE CARD",
  "VERVE GLOBAL",
  "VIET NAM",
  "VIETNAM",
  "VIRGIN ISLANDS, BRITISH",
  "VIRGIN ISLANDS, U.S.",
  "VIRTUAL",
  "VOUCHER",
  "VPAY",
  "WHITE EMV INTERBANCAIRE",
  "WORLD",
  "WORLD BLACK",
  "WORLD BLACK EDITION",
  "WORLD BUSINESS",
  "WORLD ELITE",
  "WORLD ELITE BUSINESS",
  "WORLD ELITE EXCLUSIVE",
  "WORLD ELITE FLEX",
  "WORLD ELITE FOR BUSINESS",
  "WORLD FLEX",
  "WORLD FOR BUSINESS",
  "WORLD REWARDS",
  "WORLD SIGNIA",
  "XINTONG CARD",
  "YANGCHENG CARD",
  "YANGTZE RIVER CARD",
  "YELLOW SEA CARD",
  "YINLU CARD",
  "YUANDU CARD",
  "ZAMBIA",
  "ZIMBABWE",
  "ZINKA"
];

export const banks = [
  "DISCOVER ISSUER",
  "AMERICAN EXPRESS US CONSUMER",
  "DISCOVER BANK",
  "FISERV SOLUTIONS, LLC",
  "YARD CARD CANADA",
  "BANK OF AMERICA, NATIONAL ASSOCIATION",
  "WELLS FARGO BANK, N.A.",
  "DC JAPAN",
  "JPMORGAN CHASE BANK, N.A.",
  "CARD SERVICES FOR CREDIT UNIONS",
  "AGRICULTURAL BANK OF CHINA",
  "BANK OF GUIYANG CO., LTD.",
  "BEST BUY - HSBC",
  "FUTURE SHOP - HSBC",
  "LUXURY JEWELLERY CLASS (LJC) - TDFS",
  "CANTREX - TDFS",
  "JACK HENRY & ASSOCIATES",
  "U.S. BANK, N.A.",
  "CASTLE BUILDING CENTRES - TDFS",
  "BOSE - TDFS",
  "CORBEIL - TDFS",
  "BEN MOSS JEWELLERS - TDFS",
  "FIDELITY INFORMATION SERVICES, INC.",
  "EURO KARTENSYSTEME GMBH",
  "FIFTH THIRD BANK",
  "DISPONIVEL",
  "CHARM DIAMOND CENTRES - TDFS",
  "MDS FOR EUROPE DEBIT ACQUIRER & NON-EUROPEAN DEBIT ISSUER",
  "AMERICAN EXPRESS",
  "ICBA BANCARD, INC.",
  "CRESCENT GOLD AND DIAMONDS - TDFS",
  "ICICI BANK",
  "BC CARD",
  "MAESTRO INTERNATIONAL",
  "SBERBANK OF RUSSIA",
  "ITAU UNIBANCO, S.A.",
  "AMERICAN EXPRESS US CARS",
  "COMPUTER SERVICES, INC.",
  "HDFC BANK",
  "BPCE",
  "MITSUBISHI UFJ NICOS CO., LTD",
  "STATE BANK OF INDIA",
  "CITIBANK N.A.",
  "JPMORGAN CHASE BANK N.A.",
  "INTL HDQTRS-CENTER OWNED",
  "DEUTSCHER SPARKASSEN- UND GIROVERBAND",
  "BANCO BRADESCO, S.A.",
  "FIRST NATIONAL BANK OF OMAHA",
  "MITSUBISHI UFJ NICOS CO., LTD.",
  "PSA PAYMENT SERVICES AUSTRIA GMBH",
  "CAPITAL ONE, NATIONAL ASSOCIATION",
  "IDBI",
  "AVIANCA",
  "AXIS BANK",
  "AXIS BANK, LTD.",
  "CREDIT UNION PAYMENT CENTER (LIMITED LIABILITY COMPANY)",
  "VTB BANK (PUBLIC JOINT-STOCK COMPANY)",
  "CU COOPERATIVE SYSTEMS, LLC",
  "PUBLIC JOINT STOCK COMPANY BANK URALSIB",
  "ICICI BANK, LTD.",
  "AMERICAN EXPRESS COMPANY",
  "CHASE BANK USA, N.A.",
  "SHINHAN CARD CO., LTD.",
  "WEX BANK",
  "SHINHAN CARD",
  "NEXI PAYMENTS SPA",
  "BANCO SANTANDER, S.A.",
  "PSCU INCORPORATED",
  "ITAU UNIBANCO HOLDING, S.A.",
  "PUBLIC JOINT-STOCK COMPANY BANK OTKRITIE FINANCIAL CORPORATION",
  "CAIXABANK, S.A.",
  "UC CARD CO., LTD.",
  "BANCO DO BRASIL, S.A.",
  "BC CARD CO., LTD.",
  "SUTTON BANK",
  "HDFC BANK, LTD.",
  "NATIONAL WESTMINSTER BANK PLC",
  "NATIXIS",
  "SHAZAM, INC.",
  "CITIBANK, N.A.",
  "U.S. BANK NATIONAL ASSOCIATION-CREDIT",
  "BANQUE FEDERATIVE DU CREDIT MUTUEL (BFCM)",
  "BANK OF AMERICA - CONSUMER CREDIT",
  "BARCLAYS BANK PLC",
  "BANK OF MONTREAL",
  "U.S. REGION",
  "PJSC ROSBANK",
  "BANK OF SCOTLAND PLC",
  "BOKF, NATIONAL ASSOCIATION",
  "STANDARD CHARTERED BANK",
  "METABANK",
  "YES BANK",
  "ROYAL BANK OF CANADA",
  "HYUNDAICARD CO., LTD.",
  "SHANGHAI PUDONG DEVELOPMENT BANK",
  "LUFTHANSA AIRPLUS SERVICEKARTEN GMBH",
  "INDUSTRIAL AND COMMERCIAL BANK OF CHINA, LTD.",
  "WELLS FARGO BANK, NATIONAL ASSOCIATION",
  "REGIONS BANK",
  "U.S. BANK NATIONAL ASSOCIATION",
  "PATHWARD, N.A.",
  "AMEX CANADA GLOBESTAR",
  "MASTERCARD FRANCE S.A.S.",
  "DC ITALY",
  "CREDIT SAISON CO., LTD.",
  "NETWORK ONLY",
  "PNC FINANCIAL SERVICES GROUP, INC.",
  "TORONTO-DOMINION BANK",
  "BANK OF AMERICA, N.A.",
  "BANCO COOPERATIVO ESPANOL, S.A.",
  "NEXI PAYMENTS S.P.A.",
  "SUMITOMO MITSUI CARD COMPANY, LTD.",
  "AMERICAN AIRLINES (AA)",
  "AER LINGUS (EI)",
  "JAPAN AIRLINES INTERNATIONAL (JL)",
  "HOPPER USA, INC.",
  "MBNA CANADACONSUMER FINANCE",
  "MASTERCAJAS, S.A.",
  "ITS BANK",
  "PATHWARD, NATIONAL ASSOCIATION",
  "DC ADRIATIC",
  "WEX INC.",
  "KB KOOKMIN CARD CO., LTD",
  "CABAL CARTAO",
  "CAIXA ECONOMICA FEDERAL",
  "CANADIAN IMPERIAL BANK OF COMMERCE",
  "BANK OF BARODA",
  "CANARA BANK",
  "SERVICE CREDIT UNION",
  "BOC CREDIT CARD (INTERNATIONAL), LTD.",
  "DC SINGAPORE",
  "BNP PARIBAS",
  "BOK FINANCIAL",
  "BANK OF INDIA",
  "UNION BANK OF INDIA",
  "WESTPAC BANKING CORPORATION",
  "CITIZENS BANK, N.A.",
  "CREDIT AGRICOLE, S.A.",
  "CITIBANK USA, N.A.",
  "BANCO BILBAO VIZCAYA ARGENTARIA S.A. (BBVA)",
  "OPTAL FINANCIAL, LTD.",
  "FIRST DATA CONO SUR, S.R.L.",
  "TELLER, A.S.",
  "PEOPLES TRUST COMPANY",
  "BANK OF CHINA, LTD.",
  "BOKIS",
  "BANCORP BANK",
  "THE BANCORP BANK, NATIONAL ASSOCIATION",
  "CITIBANK",
  "MBANK, S.A.",
  "PREPAY TECHNOLOGIES, LTD.",
  "CSCBANK SAL",
  "DC AUSTRALIA",
  "THE HONGKONG AND SHANGHAI BANKING CORPORATION, LTD.",
  "PUNJAB NATIONAL BANK",
  "CORNER BANCA, S.A.",
  "KEYBANK NATIONAL ASSOCIATION",
  "SOCIETE MONETIQUE-TUNISIE",
  "BANCOLOMBIA, S.A.",
  "FIRSTRAND BANK, LTD.",
  "ENTROPAY, LTD.",
  "FIRST ABU DHABI BANK PJSC",
  "FIRST HORIZON BANK",
  "DZ BANK AG",
  "FIRST INTERSTATE BANK",
  "BANCO BRADESCARD, S.A.",
  "CITIBANK (HONG KONG), LTD.",
  "AMERICAN EXPRESS JAPAN",
  "ROYAL BANK OF SCOTLAND PLC",
  "BANK OF NOVA SCOTIA",
  "SERVIRED, SOCIEDAD ESPANOLA DE MEDIOS DE PAGO S.A.",
  "BANCO BRADESCO",
  "AMEX UK GLOBESTAR",
  "BANCO POPULAR ESPANOL, S.A.",
  "BAWAG P.S.K. BANK",
  "STANDARD BANK OF SOUTH AFRICA, LTD.",
  "YES BANK, LTD.",
  "BANCO PROMERICA, S.A.",
  "BC CARD COMPANY, LTD.",
  "COMMONWEALTH BANK OF AUSTRALIA",
  "CN ICBC PEONY MONEY LINK CARD",
  "OPTAL FINANCIAL EUROPE, LTD.",
  "AEC MEXICO SA DE CV - GSTAR CONS CHARGE",
  "PNC BANK, NATIONAL ASSOCIATION",
  "DATA CENTER INCORPORATED",
  "CHINA GUANGFA BANK CO., LTD.",
  "LOTTE CARD CO., LTD.",
  "CLEARVIEW FEDERAL CREDIT UNION",
  "REPUBLIC BANK & TRUST COMPANY",
  "SOCIETE GENERALE, S.A.",
  "DEUTSCHE BANK S.P.A.",
  "BANCO DAVIVIENDA, S.A.",
  "DEUTSCHE BANK AG",
  "SIA S.P.A.",
  "CUSCAL, LTD.",
  "HSBC BANK MIDDLE EAST",
  "CREDIT MUTUEL ARKEA",
  "VISA NORGE A/S",
  "PIRAEUS BANK, S.A.",
  "UAB FINANSINES PASLAUGOS CONTIS",
  "TRANSACT PAYMENTS, LTD.",
  "SAMSUNG CARD CO., LTD.",
  "BMO HARRIS BANK, N.A.",
  "HANA CARD",
  "JPMORGAN CHASE BANK N.A. - DEBIT",
  "VISA EUROPE, LTD.",
  "KEYBANK, N.A.",
  "CU COOPERATIVE SYSTEMS",
  "PNC BANK, NATIONAL ASSOCIATION - CONSUMER CREDIT",
  "INDUSTRIAL AND COMMERCIAL BANK OF CHINA",
  "SBI CARDS AND PAYMENT SERVICES, LTD.",
  "CITIBANK, NATIONAL ASSOCIATION - CONSUMER",
  "ABSA GROUP, LTD.",
  "UNITED BANK FOR AFRICA PLC",
  "LLOYDS BANK PLC",
  "FIRSTCARIBBEAN INTERNATIONAL BANK (BARBADOS), LTD.",
  "BANCO POPULAR DE PUERTO RICO",
  "SOUTHWEST AIRLINES FEDERAL CREDIT UNION",
  "BANCO INDUSTRIAL, S.A.",
  "DOCK INSTITUICAO DE PAGAMENTO, S.A.",
  "EUROPAY LUXEMBOURG S.C.",
  "BANK OF AMERICA",
  "ISTITUTO CENTRALE DELLE BANCHE DI CREDITO COOPERATIVO (ICCREA)",
  "HONG KONG AND SHANGHAI BANKING CORP., LTD.",
  "YAPI VE KREDI BANKASI, A.S.",
  "THE BANCORP BANK NATIONAL ASSOCIATION",
  "STARBUCKS CARD",
  "CHINA CONSTRUCTION BANK",
  "BANK OF CHINA",
  "AEBC INDIA - GSTAR CONS REVOLVE",
  "HYUNDAI CARD COMPANY, LTD.",
  "NATIONAL AUSTRALIA BANK, LTD.",
  "AEROPLAN (AIR CANADA)",
  "PAYPAL",
  "EASYPAY",
  "DC ECUADOR",
  "CONTINENTAL AIRLINES (CO)",
  "DELTA AIRLINES (DL)",
  "UNITED AIRLINES (UA)",
  "SAUDI ARABIAN AIRLINES (SV)",
  "IBERIA LINEAS AEREAS DE ESPANA",
  "QANTAS AIRWAYS (QF)",
  "AIR NEW ZEALAND (NZ)",
  "FINNAIR OYJ (AY)",
  "EL AL ISRAELI AIRLINES (LY)",
  "BRITISH AIRWAYS (BA)",
  "GOL LINHAS AEREAS INTELIGENTES (G3)",
  "AEROMEXICO (AM)",
  "QATAR AIRWAYS (QR)",
  "HAHN AIR BUSINESS LINE (HR)",
  "AERTICKET GMBH",
  "MALAYSIA AIRLINES (MH)",
  "SHANDONG AIRLINES (SC)",
  "TURKISH AIRLINES (TK)",
  "AUSTRIAN AIRLINES (OS)",
  "WEGO PTE, LTD.",
  "APG AIRLINES",
  "CONNEXPAY, LLC.",
  "MONETA",
  "YATRA ONLINE, LTD.",
  "DELTA AIR LINES (DL)",
  "ETIHAD AIRWAYS (EY)",
  "TUIFLY GMBH (HF)",
  "AIR NIUGINI",
  "EVA AIRWAYS CORPORATION",
  "CHINA EASTERN AIRLINES (MU)",
  "AKBAR TRAVELS",
  "AUSTRALIAN AIRLINES (OS)",
  "AIR CHINA",
  "NETWORK INTERNATIONAL LLC",
  "DC COLOMBIA",
  "WALMART CANADA",
  "CHONGQING BANK",
  "JCB CO., LTD.",
  "SYNCHRONY BANK",
  "BNP PARIBAS BANK POLSKA, S.A.",
  "BANCO BRADESCO SA",
  "ING",
  "BPSUPERCHARGE",
  "CHINA MERCHANTS BANK",
  "THE BANK OF NOVA SCOTIA",
  "HSBC BANK PLC",
  "CNH CAPITAL REVOLVING ACCOUNT",
  "DC PERU",
  "CATHAY PACIFIC",
  "BARCLAYS BANK DELAWARE",
  "TRELLANCE, INC.",
  "LA BANQUE POSTALE",
  "AMEX UK CONSUMER CHARGE",
  "AMEX GERMANY GLOBESTAR CHARGE",
  "SUNTRUST BANK",
  "PAYRNET, LTD.",
  "GE MONEY CANADA",
  "PAYSQUARE SE",
  "NEDBANK, LTD.",
  "ARAB BANK PLC",
  "SANTANDER BANK POLSKA, S.A.",
  "DANSKE BANK A/S",
  "COMERICA BANK",
  "AMEX FRANCE GLOBESTAR CHARGE"
];

export const countries = [
  {
    "code": "AF",
    "name": "AFGHANISTAN",
    "flag": "🇦🇫"
  },
  {
    "code": "AL",
    "name": "ALBANIA",
    "flag": "🇦🇱"
  },
  {
    "code": "DZ",
    "name": "ALGERIA",
    "flag": "🇩🇿"
  },
  {
    "code": "AS",
    "name": "AMERICAN SAMOA",
    "flag": "🇦🇸"
  },
  {
    "code": "AD",
    "name": "ANDORRA",
    "flag": "🇦🇩"
  },
  {
    "code": "AO",
    "name": "ANGOLA",
    "flag": "🇦🇴"
  },
  {
    "code": "AI",
    "name": "ANGUILLA",
    "flag": "🇦🇮"
  },
  {
    "code": "AG",
    "name": "ANTIGUA AND BARBUDA",
    "flag": "🇦🇬"
  },
  {
    "code": "AR",
    "name": "ARGENTINA",
    "flag": "🇦🇷"
  },
  {
    "code": "AM",
    "name": "ARMENIA",
    "flag": "🇦🇲"
  },
  {
    "code": "AW",
    "name": "ARUBA",
    "flag": "🇦🇼"
  },
  {
    "code": "AU",
    "name": "AUSTRALIA",
    "flag": "🇦🇺"
  },
  {
    "code": "AT",
    "name": "AUSTRIA",
    "flag": "🇦🇹"
  },
  {
    "code": "AZ",
    "name": "AZERBAIJAN",
    "flag": "🇦🇿"
  },
  {
    "code": "BS",
    "name": "BAHAMAS",
    "flag": "🇧🇸"
  },
  {
    "code": "BH",
    "name": "BAHRAIN",
    "flag": "🇧🇭"
  },
  {
    "code": "BD",
    "name": "BANGLADESH",
    "flag": "🇧🇩"
  },
  {
    "code": "BB",
    "name": "BARBADOS",
    "flag": "🇧🇧"
  },
  {
    "code": "BY",
    "name": "BELARUS",
    "flag": "🇧🇾"
  },
  {
    "code": "BE",
    "name": "BELGIUM",
    "flag": "🇧🇪"
  },
  {
    "code": "BZ",
    "name": "BELIZE",
    "flag": "🇧🇿"
  },
  {
    "code": "BJ",
    "name": "BENIN",
    "flag": "🇧🇯"
  },
  {
    "code": "BM",
    "name": "BERMUDA",
    "flag": "🇧🇲"
  },
  {
    "code": "BT",
    "name": "BHUTAN",
    "flag": "🇧🇹"
  },
  {
    "code": "BO",
    "name": "BOLIVIA, PLURINATIONAL STATE OF",
    "flag": "🇧🇴"
  },
  {
    "code": "BQ",
    "name": "BONAIRE, SINT EUSTATIUS AND SABA",
    "flag": "🇧🇶"
  },
  {
    "code": "BA",
    "name": "BOSNIA AND HERZEGOVINA",
    "flag": "🇧🇦"
  },
  {
    "code": "BW",
    "name": "BOTSWANA",
    "flag": "🇧🇼"
  },
  {
    "code": "BR",
    "name": "BRAZIL",
    "flag": "🇧🇷"
  },
  {
    "code": "BN",
    "name": "BRUNEI DARUSSALAM",
    "flag": "🇧🇳"
  },
  {
    "code": "BG",
    "name": "BULGARIA",
    "flag": "🇧🇬"
  },
  {
    "code": "BF",
    "name": "BURKINA FASO",
    "flag": "🇧🇫"
  },
  {
    "code": "BI",
    "name": "BURUNDI",
    "flag": "🇧🇮"
  },
  {
    "code": "CV",
    "name": "CABO VERDE",
    "flag": "🇨🇻"
  },
  {
    "code": "KH",
    "name": "CAMBODIA",
    "flag": "🇰🇭"
  },
  {
    "code": "CM",
    "name": "CAMEROON",
    "flag": "🇨🇲"
  },
  {
    "code": "CA",
    "name": "CANADA",
    "flag": "🇨🇦"
  },
  {
    "code": "KY",
    "name": "CAYMAN ISLANDS",
    "flag": "🇰🇾"
  },
  {
    "code": "CF",
    "name": "CENTRAL AFRICAN REPUBLIC",
    "flag": "🇨🇫"
  },
  {
    "code": "TD",
    "name": "CHAD",
    "flag": "🇹🇩"
  },
  {
    "code": "CL",
    "name": "CHILE",
    "flag": "🇨🇱"
  },
  {
    "code": "CN",
    "name": "CHINA",
    "flag": "🇨🇳"
  },
  {
    "code": "CO",
    "name": "COLOMBIA",
    "flag": "🇨🇴"
  },
  {
    "code": "KM",
    "name": "COMOROS",
    "flag": "🇰🇲"
  },
  {
    "code": "CG",
    "name": "CONGO",
    "flag": "🇨🇬"
  },
  {
    "code": "CD",
    "name": "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
    "flag": "🇨🇩"
  },
  {
    "code": "CK",
    "name": "COOK ISLANDS",
    "flag": "🇨🇰"
  },
  {
    "code": "CR",
    "name": "COSTA RICA",
    "flag": "🇨🇷"
  },
  {
    "code": "CI",
    "name": "COTE D'IVOIRE",
    "flag": "🇨🇮"
  },
  {
    "code": "HR",
    "name": "CROATIA",
    "flag": "🇭🇷"
  },
  {
    "code": "CU",
    "name": "CUBA",
    "flag": "🇨🇺"
  },
  {
    "code": "CW",
    "name": "CURACAO",
    "flag": "🇨🇼"
  },
  {
    "code": "CY",
    "name": "CYPRUS",
    "flag": "🇨🇾"
  },
  {
    "code": "CZ",
    "name": "CZECH REPUBLIC",
    "flag": "🇨🇿"
  },
  {
    "code": "DK",
    "name": "DENMARK",
    "flag": "🇩🇰"
  },
  {
    "code": "DJ",
    "name": "DJIBOUTI",
    "flag": "🇩🇯"
  },
  {
    "code": "DM",
    "name": "DOMINICA",
    "flag": "🇩🇲"
  },
  {
    "code": "DO",
    "name": "DOMINICAN REPUBLIC",
    "flag": "🇩🇴"
  },
  {
    "code": "EC",
    "name": "ECUADOR",
    "flag": "🇪🇨"
  },
  {
    "code": "EG",
    "name": "EGYPT",
    "flag": "🇪🇬"
  },
  {
    "code": "SV",
    "name": "EL SALVADOR",
    "flag": "🇸🇻"
  },
  {
    "code": "GQ",
    "name": "EQUATORIAL GUINEA",
    "flag": "🇬🇶"
  },
  {
    "code": "ER",
    "name": "ERITREA",
    "flag": "🇪🇷"
  },
  {
    "code": "EE",
    "name": "ESTONIA",
    "flag": "🇪🇪"
  },
  {
    "code": "ET",
    "name": "ETHIOPIA",
    "flag": "🇪🇹"
  },
  {
    "code": "FK",
    "name": "FALKLAND ISLANDS (MALVINAS)",
    "flag": "🇫🇰"
  },
  {
    "code": "FJ",
    "name": "FIJI",
    "flag": "🇫🇯"
  },
  {
    "code": "FI",
    "name": "FINLAND",
    "flag": "🇫🇮"
  },
  {
    "code": "FR",
    "name": "FRANCE",
    "flag": "🇫🇷"
  },
  {
    "code": "PF",
    "name": "FRENCH POLYNESIA",
    "flag": "🇵🇫"
  },
  {
    "code": "GA",
    "name": "GABON",
    "flag": "🇬🇦"
  },
  {
    "code": "GM",
    "name": "GAMBIA",
    "flag": "🇬🇲"
  },
  {
    "code": "GE",
    "name": "GEORGIA",
    "flag": "🇬🇪"
  },
  {
    "code": "DE",
    "name": "GERMANY",
    "flag": "🇩🇪"
  },
  {
    "code": "GH",
    "name": "GHANA",
    "flag": "🇬🇭"
  },
  {
    "code": "GI",
    "name": "GIBRALTAR",
    "flag": "🇬🇮"
  },
  {
    "code": "GR",
    "name": "GREECE",
    "flag": "🇬🇷"
  },
  {
    "code": "GD",
    "name": "GRENADA",
    "flag": "🇬🇩"
  },
  {
    "code": "GU",
    "name": "GUAM",
    "flag": "🇬🇺"
  },
  {
    "code": "GT",
    "name": "GUATEMALA",
    "flag": "🇬🇹"
  },
  {
    "code": "GG",
    "name": "GUERNSEY",
    "flag": "🇬🇬"
  },
  {
    "code": "GN",
    "name": "GUINEA",
    "flag": "🇬🇳"
  },
  {
    "code": "GW",
    "name": "GUINEA-BISSAU",
    "flag": "🇬🇼"
  },
  {
    "code": "GY",
    "name": "GUYANA",
    "flag": "🇬🇾"
  },
  {
    "code": "HT",
    "name": "HAITI",
    "flag": "🇭🇹"
  },
  {
    "code": "VA",
    "name": "HOLY SEE (VATICAN CITY STATE)",
    "flag": "🇻🇦"
  },
  {
    "code": "HN",
    "name": "HONDURAS",
    "flag": "🇭🇳"
  },
  {
    "code": "HK",
    "name": "HONG KONG",
    "flag": "🇭🇰"
  },
  {
    "code": "HU",
    "name": "HUNGARY",
    "flag": "🇭🇺"
  },
  {
    "code": "IS",
    "name": "ICELAND",
    "flag": "🇮🇸"
  },
  {
    "code": "IN",
    "name": "INDIA",
    "flag": "🇮🇳"
  },
  {
    "code": "ID",
    "name": "INDONESIA",
    "flag": "🇮🇩"
  },
  {
    "code": "IR",
    "name": "IRAN, ISLAMIC REPUBLIC OF",
    "flag": "🇮🇷"
  },
  {
    "code": "IQ",
    "name": "IRAQ",
    "flag": "🇮🇶"
  },
  {
    "code": "IE",
    "name": "IRELAND",
    "flag": "🇮🇪"
  },
  {
    "code": "IM",
    "name": "ISLE OF MAN",
    "flag": "🇮🇲"
  },
  {
    "code": "IL",
    "name": "ISRAEL",
    "flag": "🇮🇱"
  },
  {
    "code": "IT",
    "name": "ITALY",
    "flag": "🇮🇹"
  },
  {
    "code": "JM",
    "name": "JAMAICA",
    "flag": "🇯🇲"
  },
  {
    "code": "JP",
    "name": "JAPAN",
    "flag": "🇯🇵"
  },
  {
    "code": "JE",
    "name": "JERSEY",
    "flag": "🇯🇪"
  },
  {
    "code": "JO",
    "name": "JORDAN",
    "flag": "🇯🇴"
  },
  {
    "code": "KZ",
    "name": "KAZAKHSTAN",
    "flag": "🇰🇿"
  },
  {
    "code": "KE",
    "name": "KENYA",
    "flag": "🇰🇪"
  },
  {
    "code": "KI",
    "name": "KIRIBATI",
    "flag": "🇰🇮"
  },
  {
    "code": "KP",
    "name": "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    "flag": "🇰🇵"
  },
  {
    "code": "KR",
    "name": "KOREA, REPUBLIC OF",
    "flag": "🇰🇷"
  },
  {
    "code": "XK",
    "name": "KOSOVO, REPUBLIC OF",
    "flag": "🇽🇰"
  },
  {
    "code": "KW",
    "name": "KUWAIT",
    "flag": "🇰🇼"
  },
  {
    "code": "KG",
    "name": "KYRGYZSTAN",
    "flag": "🇰🇬"
  },
  {
    "code": "LA",
    "name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    "flag": "🇱🇦"
  },
  {
    "code": "LV",
    "name": "LATVIA",
    "flag": "🇱🇻"
  },
  {
    "code": "LB",
    "name": "LEBANON",
    "flag": "🇱🇧"
  },
  {
    "code": "LS",
    "name": "LESOTHO",
    "flag": "🇱🇸"
  },
  {
    "code": "LR",
    "name": "LIBERIA",
    "flag": "🇱🇷"
  },
  {
    "code": "LY",
    "name": "LIBYAN ARAB JAMAHIRIYA",
    "flag": "🇱🇾"
  },
  {
    "code": "LI",
    "name": "LIECHTENSTEIN",
    "flag": "🇱🇮"
  },
  {
    "code": "LT",
    "name": "LITHUANIA",
    "flag": "🇱🇹"
  },
  {
    "code": "LU",
    "name": "LUXEMBOURG",
    "flag": "🇱🇺"
  },
  {
    "code": "MO",
    "name": "MACAO",
    "flag": "🇲🇴"
  },
  {
    "code": "MK",
    "name": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
    "flag": "🇲🇰"
  },
  {
    "code": "MG",
    "name": "MADAGASCAR",
    "flag": "🇲🇬"
  },
  {
    "code": "MW",
    "name": "MALAWI",
    "flag": "🇲🇼"
  },
  {
    "code": "MY",
    "name": "MALAYSIA",
    "flag": "🇲🇾"
  },
  {
    "code": "MV",
    "name": "MALDIVES",
    "flag": "🇲🇻"
  },
  {
    "code": "ML",
    "name": "MALI",
    "flag": "🇲🇱"
  },
  {
    "code": "MT",
    "name": "MALTA",
    "flag": "🇲🇹"
  },
  {
    "code": "MH",
    "name": "MARSHALL ISLANDS",
    "flag": "🇲🇭"
  },
  {
    "code": "MQ",
    "name": "MARTINIQUE",
    "flag": "🇲🇶"
  },
  {
    "code": "MR",
    "name": "MAURITANIA",
    "flag": "🇲🇷"
  },
  {
    "code": "MU",
    "name": "MAURITIUS",
    "flag": "🇲🇺"
  },
  {
    "code": "YT",
    "name": "MAYOTTE",
    "flag": "🇾🇹"
  },
  {
    "code": "MX",
    "name": "MEXICO",
    "flag": "🇲🇽"
  },
  {
    "code": "FM",
    "name": "MICRONESIA, FEDERATED STATES OF",
    "flag": "🇫🇲"
  },
  {
    "code": "MD",
    "name": "MOLDOVA, REPUBLIC OF",
    "flag": "🇲🇩"
  },
  {
    "code": "MC",
    "name": "MONACO",
    "flag": "🇲🇨"
  },
  {
    "code": "MN",
    "name": "MONGOLIA",
    "flag": "🇲🇳"
  },
  {
    "code": "ME",
    "name": "MONTENEGRO",
    "flag": "🇲🇪"
  },
  {
    "code": "MS",
    "name": "MONTSERRAT",
    "flag": "🇲🇸"
  },
  {
    "code": "MA",
    "name": "MOROCCO",
    "flag": "🇲🇦"
  },
  {
    "code": "MZ",
    "name": "MOZAMBIQUE",
    "flag": "🇲🇿"
  },
  {
    "code": "MM",
    "name": "MYANMAR",
    "flag": "🇲🇲"
  },
  {
    "code": "NA",
    "name": "NAMIBIA",
    "flag": "🇳🇦"
  },
  {
    "code": "NR",
    "name": "NAURU",
    "flag": "🇳🇷"
  },
  {
    "code": "NP",
    "name": "NEPAL",
    "flag": "🇳🇵"
  },
  {
    "code": "NL",
    "name": "NETHERLANDS",
    "flag": "🇳🇱"
  },
  {
    "code": "NC",
    "name": "NEW CALEDONIA",
    "flag": "🇳🇨"
  },
  {
    "code": "NZ",
    "name": "NEW ZEALAND",
    "flag": "🇳🇿"
  },
  {
    "code": "NI",
    "name": "NICARAGUA",
    "flag": "🇳🇮"
  },
  {
    "code": "NE",
    "name": "NIGER",
    "flag": "🇳🇪"
  },
  {
    "code": "NG",
    "name": "NIGERIA",
    "flag": "🇳🇬"
  },
  {
    "code": "MP",
    "name": "NORTHERN MARIANA ISLANDS",
    "flag": "🇲🇵"
  },
  {
    "code": "NO",
    "name": "NORWAY",
    "flag": "🇳🇴"
  },
  {
    "code": "OM",
    "name": "OMAN",
    "flag": "🇴🇲"
  },
  {
    "code": "PK",
    "name": "PAKISTAN",
    "flag": "🇵🇰"
  },
  {
    "code": "PW",
    "name": "PALAU",
    "flag": "🇵🇼"
  },
  {
    "code": "PS",
    "name": "PALESTINIAN TERRITORY, OCCUPIED",
    "flag": "🇵🇸"
  },
  {
    "code": "PA",
    "name": "PANAMA",
    "flag": "🇵🇦"
  },
  {
    "code": "PG",
    "name": "PAPUA NEW GUINEA",
    "flag": "🇵🇬"
  },
  {
    "code": "PY",
    "name": "PARAGUAY",
    "flag": "🇵🇾"
  },
  {
    "code": "PE",
    "name": "PERU",
    "flag": "🇵🇪"
  },
  {
    "code": "PH",
    "name": "PHILIPPINES",
    "flag": "🇵🇭"
  },
  {
    "code": "PL",
    "name": "POLAND",
    "flag": "🇵🇱"
  },
  {
    "code": "PT",
    "name": "PORTUGAL",
    "flag": "🇵🇹"
  },
  {
    "code": "PR",
    "name": "PUERTO RICO",
    "flag": "🇵🇷"
  },
  {
    "code": "QA",
    "name": "QATAR",
    "flag": "🇶🇦"
  },
  {
    "code": "RE",
    "name": "REUNION",
    "flag": "🇷🇪"
  },
  {
    "code": "RO",
    "name": "ROMANIA",
    "flag": "🇷🇴"
  },
  {
    "code": "RU",
    "name": "RUSSIAN FEDERATION",
    "flag": "🇷🇺"
  },
  {
    "code": "RW",
    "name": "RWANDA",
    "flag": "🇷🇼"
  },
  {
    "code": "KN",
    "name": "SAINT KITTS AND NEVIS",
    "flag": "🇰🇳"
  },
  {
    "code": "LC",
    "name": "SAINT LUCIA",
    "flag": "🇱🇨"
  },
  {
    "code": "VC",
    "name": "SAINT VINCENT AND THE GRENADINES",
    "flag": "🇻🇨"
  },
  {
    "code": "WS",
    "name": "SAMOA",
    "flag": "🇼🇸"
  },
  {
    "code": "SM",
    "name": "SAN MARINO",
    "flag": "🇸🇲"
  },
  {
    "code": "ST",
    "name": "SAO TOME AND PRINCIPE",
    "flag": "🇸🇹"
  },
  {
    "code": "SA",
    "name": "SAUDI ARABIA",
    "flag": "🇸🇦"
  },
  {
    "code": "SN",
    "name": "SENEGAL",
    "flag": "🇸🇳"
  },
  {
    "code": "RS",
    "name": "SERBIA",
    "flag": "🇷🇸"
  },
  {
    "code": "SC",
    "name": "SEYCHELLES",
    "flag": "🇸🇨"
  },
  {
    "code": "SL",
    "name": "SIERRA LEONE",
    "flag": "🇸🇱"
  },
  {
    "code": "SG",
    "name": "SINGAPORE",
    "flag": "🇸🇬"
  },
  {
    "code": "SX",
    "name": "SINT MAARTEN (DUTCH PART)",
    "flag": "🇸🇽"
  },
  {
    "code": "SK",
    "name": "SLOVAKIA",
    "flag": "🇸🇰"
  },
  {
    "code": "SI",
    "name": "SLOVENIA",
    "flag": "🇸🇮"
  },
  {
    "code": "SB",
    "name": "SOLOMON ISLANDS",
    "flag": "🇸🇧"
  },
  {
    "code": "SO",
    "name": "SOMALIA",
    "flag": "🇸🇴"
  },
  {
    "code": "ZA",
    "name": "SOUTH AFRICA",
    "flag": "🇿🇦"
  },
  {
    "code": "SS",
    "name": "SOUTH SUDAN",
    "flag": "🇸🇸"
  },
  {
    "code": "ES",
    "name": "SPAIN",
    "flag": "🇪🇸"
  },
  {
    "code": "LK",
    "name": "SRI LANKA",
    "flag": "🇱🇰"
  },
  {
    "code": "SD",
    "name": "SUDAN",
    "flag": "🇸🇩"
  },
  {
    "code": "SR",
    "name": "SURINAME",
    "flag": "🇸🇷"
  },
  {
    "code": "SZ",
    "name": "SWAZILAND",
    "flag": "🇸🇿"
  },
  {
    "code": "SE",
    "name": "SWEDEN",
    "flag": "🇸🇪"
  },
  {
    "code": "CH",
    "name": "SWITZERLAND",
    "flag": "🇨🇭"
  },
  {
    "code": "SY",
    "name": "SYRIAN ARAB REPUBLIC",
    "flag": "🇸🇾"
  },
  {
    "code": "TW",
    "name": "TAIWAN, PROVINCE OF CHINA",
    "flag": "🇹🇼"
  },
  {
    "code": "TJ",
    "name": "TAJIKISTAN",
    "flag": "🇹🇯"
  },
  {
    "code": "TZ",
    "name": "TANZANIA, UNITED REPUBLIC OF",
    "flag": "🇹🇿"
  },
  {
    "code": "TH",
    "name": "THAILAND",
    "flag": "🇹🇭"
  },
  {
    "code": "TL",
    "name": "TIMOR-LESTE",
    "flag": "🇹🇱"
  },
  {
    "code": "TG",
    "name": "TOGO",
    "flag": "🇹🇬"
  },
  {
    "code": "TO",
    "name": "TONGA",
    "flag": "🇹🇴"
  },
  {
    "code": "TT",
    "name": "TRINIDAD AND TOBAGO",
    "flag": "🇹🇹"
  },
  {
    "code": "TN",
    "name": "TUNISIA",
    "flag": "🇹🇳"
  },
  {
    "code": "TR",
    "name": "TURKEY",
    "flag": "🇹🇷"
  },
  {
    "code": "TM",
    "name": "TURKMENISTAN",
    "flag": "🇹🇲"
  },
  {
    "code": "TC",
    "name": "TURKS AND CAICOS ISLANDS",
    "flag": "🇹🇨"
  },
  {
    "code": "UG",
    "name": "UGANDA",
    "flag": "🇺🇬"
  },
  {
    "code": "UA",
    "name": "UKRAINE",
    "flag": "🇺🇦"
  },
  {
    "code": "AE",
    "name": "UNITED ARAB EMIRATES",
    "flag": "🇦🇪"
  },
  {
    "code": "GB",
    "name": "UNITED KINGDOM",
    "flag": "🇬🇧"
  },
  {
    "code": "US",
    "name": "UNITED STATES",
    "flag": "🇺🇸"
  },
  {
    "code": "UM",
    "name": "UNITED STATES MINOR OUTLYING ISLANDS",
    "flag": "🇺🇲"
  },
  {
    "code": "UY",
    "name": "URUGUAY",
    "flag": "🇺🇾"
  },
  {
    "code": "UZ",
    "name": "UZBEKISTAN",
    "flag": "🇺🇿"
  },
  {
    "code": "VU",
    "name": "VANUATU",
    "flag": "🇻🇺"
  },
  {
    "code": "VE",
    "name": "VENEZUELA, BOLIVARIAN REPUBLIC OF",
    "flag": "🇻🇪"
  },
  {
    "code": "VN",
    "name": "VIET NAM",
    "flag": "🇻🇳"
  },
  {
    "code": "VG",
    "name": "VIRGIN ISLANDS, BRITISH",
    "flag": "🇻🇬"
  },
  {
    "code": "VI",
    "name": "VIRGIN ISLANDS, U.S.",
    "flag": "🇻🇮"
  },
  {
    "code": "YE",
    "name": "YEMEN",
    "flag": "🇾🇪"
  },
  {
    "code": "ZM",
    "name": "ZAMBIA",
    "flag": "🇿🇲"
  },
  {
    "code": "ZW",
    "name": "ZIMBABWE",
    "flag": "🇿🇼"
  }
];
